In [1]:
import numpy as np

In [2]:
firstArray=np.array([45,67,32,21,89,54])

In [7]:
firstArray.max()

89

In [4]:
print(firstArray)

[45 67 32 21 89 54]


In [18]:
secondArray=np.arange(0,100,3)

In [19]:
secondArray

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
firstArray.ndim

1

In [22]:
firstArray.shape

(6,)

In [23]:
len(firstArray)

6

In [12]:
b=np.array([23,34,12])

In [13]:
b

array([23, 34, 12])

In [15]:
b.ndim

1

In [14]:
b.shape

(3,)

In [33]:
len(b)

2

In [35]:
c=np.array([[[6,7],[34,23]],[[12,78],[67,45]]])

In [36]:
print(c)

[[[ 6  7]
  [34 23]]

 [[12 78]
  [67 45]]]


In [37]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [38]:
L=range(1000)
%timeit [i%2==0 for i in L]

72.8 µs ± 3.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [39]:
L=np.arange(1000)
%timeit L%2==0

5.06 µs ± 355 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
c.ndim

3

In [41]:
c.shape

(2, 2, 2)

In [44]:
d=(c.sort)

In [45]:
d

<function ndarray.sort>

In [46]:
print(d)

<built-in method sort of numpy.ndarray object at 0x0000026485CD60D0>


In [47]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [48]:
One=np.ones((3,3))

In [49]:
One

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
Two=np.eye(3)
Two

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
j=np.random.randn(5)

In [52]:
j

array([ 1.27451017,  0.93549549, -1.41016109,  1.75767899,  1.16088738])

In [60]:
firstArray

array([45, 67, 32, 21,  0, 54])

In [55]:
TA=firstArray[::-1]

In [59]:
TA

array([54,  0, 21, 32, 67, 45])

In [58]:
TA[1]=0

In [61]:
id(firstArray)

2630724826336

In [62]:
id(TA)

2630764966896

In [3]:
arr1=np.arange(10)

In [4]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2=arr1[::2]

In [6]:
arr2

array([0, 2, 4, 6, 8])

In [7]:
np.shares_memory(arr1,arr2)

True

In [8]:
arr2[0]=10
arr2

array([10,  2,  4,  6,  8])

In [9]:
arr1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [2]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [4]:
b=np.ones(4)+1

In [7]:
a**2-b

array([-1.,  2.,  7., 14.])

In [6]:
b

array([2., 2., 2., 2.])

In [8]:
c=np.diag([1,2,3,4])

In [9]:
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
print(c*c)
print("************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [12]:
a==b

array([False,  True, False, False])

In [13]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [14]:
np.logical_and(a,b)

array([ True, False, False, False])

In [16]:
f=np.array([[1,2,3],[4,5,6]])

In [17]:
f.ravel()

array([1, 2, 3, 4, 5, 6])

In [20]:
f.T.ravel().reshape(2,3)

array([[1, 4, 2],
       [5, 3, 6]])